In [1]:
import numpy as np


In [2]:
np.zeros(3)

array([0., 0., 0.])

In [3]:
np.ones(3)

array([1., 1., 1.])

In [4]:
np.empty(6)

array([1.04923491e+165, 5.28802793e+174, 1.42280357e+160, 5.25196357e+170,
       2.12199579e-314, 3.25060610e-319])

In [5]:
np.empty(5)

array([2.12199579e-314, 3.83498818e+151, 4.98018171e-321, 3.79442416e-321,
       0.00000000e+000])

In [6]:
np.arange(3,31,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])